### ISSUE TITLE
HttpRequestMethodNotSupportedException

### ISSUE THREAD

**Issue by neshant** [wimdeblauwe/error-handling-spring-boot-starter#54]
Out of the box when I make an API call to a method not implemented yet, HttpRequestMethodNotSupportedException exception is thrown which does not get handled and Spring handles this exception with its own handler and formats with the big stack trace and message 

  "error": "Method Not Allowed",
  "message": "Request method 'GET' not supported",
   "path": "/v1/api"

I tried to override it following examples 

```
    http-statuses:
      org:
        springframework:
          web:
            HttpRequestMethodNotSupportedException: method_not_allowed
```

However it did not work .I think it is likely because Spring handles this exception before any of the custom exception handler can get to it. If that is what is happening I think it is better to register custom handlers before spring handlers with something like this `@Order(Ordered.HIGHEST_PRECEDENCE)`
