### ISSUE TITLE
Spring Security exceptions return an empty body

### ISSUE THREAD

**Issue by donalmurtagh** [wimdeblauwe/error-handling-spring-boot-starter#94]
According to [section 3.5.5 ](https://wimdeblauwe.github.io/error-handling-spring-boot-starter/current/#spring-security-exceptions), when a Spring Security exception is thrown, a response body with a code and a message should be returned.

In my app, I have the following filter

```java
public class JwtAuthenticationFilter extends UsernamePasswordAuthenticationFilter {

    @Autowired
    private final AuthenticationManager authenticationManager;

    @Autowired
    private final ObjectMapper objectMapper;

    @Override
    public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) {

        try (var requestBody = request.getInputStream()) {
            var loginDetails = objectMapper.readValue(requestBody, LoginDetails.class);

            try {
                var authToken = new UsernamePasswordAuthenticationToken(loginDetails.username(), loginDetails.password());
                return authenticationManager.authenticate(authToken);

            } catch (BadCredentialsException | LockedException ex) {
                throw ex;
            }
        } catch (IOException ex) {
            throw new AuthenticationServiceException("Failed to read login details from request body", ex);
        }
    }
}
```

When a LockedException is thrown, the response has a 401 status, but the body is empty. I tried changing the code to throw a `DisabledException` instead, but it also returns an empty response body.

I've appended my error handling configuration below

```yaml
error:
  handling:
    handle-filter-chain-exceptions: true
    http-statuses:
      io.jsonwebtoken.ExpiredJwtException: unauthorized
      org.springframework.web.bind.MethodArgumentNotValidException: bad_request
      org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: bad_request
      org.springframework.web.multipart.support.MissingServletRequestPartException: bad_request
      org.springframework.http.converter.HttpMessageConversionException: bad_request
      org.springframework.security.access.AccessDeniedException: forbidden
      org.springframework.dao.DataIntegrityViolationException: conflict
      jakarta.validation.ValidationException: bad_request
      java.util.NoSuchElementException: not_found
    full-stacktrace-http-statuses[0]: 5xx
    search-super-class-hierarchy: true
```

## Investigation

I did some debugging and it seems that the exception is never propagated to `FilterChainExceptionHandlerFilter` because it's handled by `AbstractAuthenticationProcessingFilter`, which is an ancestor of `JwtAuthenticationFilter`
